Added callout on personal access token
ms1-learner/cpp-01-en pull request #9
Opened 2023-11-24 05:43 UTC by dancer-yuma

## What I changed

- added a callout on personal access token to be used for password authentication in README

2023-11-27 03:48 UTC, abolinsky requested changes

2023-11-27 03:48 UTC, abolinsky commented on README.md
> +> You may be asked to enter password and encounter the following error. To fix this, you have to use personal access token for password authentication. More information is available on [the official
You may be asked to enter your GitHub account username and password and encounter the following error.

```sh
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/ms1-learner/cpp-01-en.git/'
```

To fix this, you must use a personal access token for authentication. Information detailing this process is available in [the official GitHub documentation](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic).

2023-11-27 06:51 UTC, lordmadi commented on README.md
> +> You may be asked to enter password and encounter the following error. To fix this, you have to use personal access token for password authentication. More information is available on [the official
I guess the flow Alex suggested is more readable. Can you change it @dancer-yuma?

2023-11-27 09:57 UTC, dancer-yuma commented on README.md
> +> You may be asked to enter password and encounter the following error. To fix this, you have to use personal access token for password authentication. More information is available on [the official
Yes! Thank you @abolinsky and @lordmadi! Working on it.

2023-11-27 10:01 UTC, dancer-yuma commented on README.md
> +> You may be asked to enter password and encounter the following error. To fix this, you have to use personal access token for password authentication. More information is available on [the official
Resolved in [1288b3b](https://github.com/ms1-learner/cpp-01-en/pull/9/commits/1288b3b5fb2f1da809fe0f0ba159110155813c56).

2023-11-28 00:57 UTC, lordmadi approved these changes
lgtm

2023-11-28 00:58 UTC, lordmadi approved these changes

2023-11-28 06:55 UTC, abolinsky approved these changes

2023-11-28 06:55 UTC, merged